stages:
  - trigger

trigger::trigger-downstream:
  stage: trigger
  inherit:
    variables: false
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
      allow_failure: false
    - if: $CI_COMMIT_BRANCH != "main"
      when: manual
      allow_failure: false

  trigger:
    project: creative/ci/uhi/unity
    branch: main
